version: '{build}'
skip_tags: true
image: Visual Studio 2019
test: off
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/ZBlazor.QuickInput.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: 3+5T+2Z10TlETuXd44nQ/I3+8L4dVYOmit62NY7kwm7kyGrUG0W3gf00zAo6hBXz
  on:
    branch: /^(master|dev)$/
